import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="max-w-lg mx-auto px-5 mt-20">
          <h1 className="text-3xl font-bold text-center">Hello World 😀</h1>
        </div>
      </main>
    </>
  );
}
